### ISSUE TITLE
Center tap should close all tool bars

### ISSUE THREAD

**Issue by seanredmond** [NYPL-Simplified/webpub-viewer#74] opened 2017-05-01 17:04 UTC
If you tap in the center to bring up the reader tool bar, then tap on the gear and change the font size, tapping in the center dismisses the second toolbar (paginated/scrolling/size) but leaves the first. You have to tap again to dismiss the first. One tap should dismiss both.

**Comment by jce1028** [comment] 2017-05-02 16:22
This may be a duplicate? or is 82 a duplicate?

**Comment by seanredmond** [comment] 2017-05-02 16:25
Yeah, they are the same issue

**Comment by aslagle** [comment] 2017-05-03 18:35
Duplicate of #82

**Closed as completed by aslagle** 2017-05-03 18:35 UTC
